matrix:
  include:
    - language: python
      python:
        - 3.5.2
      services: mysql
      before_install:
        - cd backend/Contraband
        - mv contraband/.env.example contraband/.env
        - mv contraband/local_settings.py contraband/local_settings_sample.py
        - mv contraband/local_settings_travis.py contraband/local_settings.py
        - mysql -e 'create database travis_db;'
      install:
        - pip3 install -r requirements.txt
      script:
        - python manage.py migrate --noinput
        - python manage.py collectstatic  --noinput
        # - python manage.py test
        - echo "Temporarily tests are disabled"
      addons:
        ssh_known_hosts: "login.tools.wmflabs.org"
      before_deploy:
        - cd ../../
        - openssl aes-256-cbc -K $encrypted_9ed13ed18199_key -iv $encrypted_9ed13ed18199_iv -in deploy_rsa.enc -out deploy_rsa -d
        - eval "$(ssh-agent -s)"
        - chmod 600 deploy_rsa
        - ssh-add deploy_rsa
        - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
      deploy:
        provider: script
        script: bash scripts/deploy_backend.sh
        on:
          branch: master
    - language: node_js
      node_js:
        - 4.2.6
      before_install:
        - cd frontend/WikiContrib-Frontend/
      install:
        - echo "npm install currently disabled"
      addons:
        ssh_known_hosts: "login.tools.wmflabs.org"
      script:
        - echo "npm test temporarily disabled"
      before_deploy:
        - cd ../../
        - openssl aes-256-cbc -K $encrypted_9ed13ed18199_key -iv $encrypted_9ed13ed18199_iv -in deploy_rsa.enc -out deploy_rsa -d
        - eval "$(ssh-agent -s)"
        - chmod 600 deploy_rsa
        - ssh-add deploy_rsa
        - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
      deploy:
        provider: script
        script: bash scripts/deploy_frontend.sh
        on:
          branch: master
