matrix:
  include:
    - language: python
      python:
        - 3.5.2
      before_install:
        - cd backend/Contraband
      install:
        - pip install -r requirements.txt
      script:
        - python manage.py test
      addons:
        ssh_known_hosts: "login.tools.wmflabs.org"
      before_deploy:
        - openssl aes-256-cbc -K $encrypted_9ed13ed18199_key -iv $encrypted_9ed13ed18199_iv -in deploy_rsa.enc -out deploy_rsa -d
        - eval "$(ssh-agent -s)"
        - chmod 600 deploy_rsa
        - ssh-add deploy_rsa
        - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
      deploy:
        provider: script
        script: bash scripts/deploy_backend.sh
        on:
          branch: master
    - language: node_js
      addons:
        ssh_known_hosts: "login.tools.wmflabs.org"
      script:
        - echo "npm test temporarily disabled"
      before_deploy:
        - openssl aes-256-cbc -K $encrypted_9ed13ed18199_key -iv $encrypted_9ed13ed18199_iv -in deploy_rsa.enc -out deploy_rsa -d
        - eval "$(ssh-agent -s)"
        - chmod 600 deploy_rsa
        - ssh-add deploy_rsa
        - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
      deploy:
        provider: script
        script: bash scripts/deploy_frontend.sh
        on:
          branch: master
